FROM node:24.15.0 AS dev
ARG UID=1000
ARG GID=1000
RUN groupmod -g ${GID} node && \
    usermod -u ${UID} -g ${GID} node
WORKDIR /app
COPY package.json package-lock.json* yarn.lock* pnpm-lock.yaml* ./

RUN --mount=type=cache,target=/home/node/.npm \
    --mount=type=cache,target=/home/node/.cache/yarn \
    --mount=type=cache,target=/home/node/.cache/pnpm \
    if [ -f package-lock.json ]; then \
        npm ci --no-audit --no-fund; \
    elif [ -f yarn.lock ]; then \
        corepack enable yarn && yarn install --frozen-lockfile --production=false; \
    elif [ -f pnpm-lock.yaml ]; then \
        corepack enable pnpm && pnpm install --frozen-lockfile; \
    else \
        echo "No lockfile found." && exit 1; \
    fi

COPY . .
ENV NODE_ENV=development
ENV WATCHPACK_POLLING=true
ENV HOSTNAME="0.0.0.0"

RUN chown -R node:node /app
USER node
EXPOSE 3000
CMD ["sh", "-c", "if [ -f package-lock.json ]; then npm run dev; elif [ -f yarn.lock ]; then yarn dev; elif [ -f pnpm-lock.yaml ]; then pnpm dev; else npm run dev; fi"]