# Dependencies
node_modules

# Next.js build output
.next
out

# Logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*

# Git
.git
.gitignore

# Editor files
.vscode
.idea

# OS files
.DS_Store
Thumbs.db


# Coverage
coverage

# Turborepo
.turbo

# Cache
.cache

# Docker
Dockerfile*
docker-compose*.yml
docker-compose*.yaml

# Documentation
README.md